language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install pip==1.5.4"
  - "pip install -r requirements/ci.txt"
  - "pip install -r requirements/unittests.txt"
# command to run tests
script: python manage.py jenkins --settings=tsune.settings.ci --verbosity 2
after_success:
  - coveralls